### 1.Setup & Import

%pip install pandas

In [1]:
#It supports series and dataframe datatypes
import pandas as pd
import numpy as np

In [5]:
pd.__version__

'3.0.6'

### 2.Creating Series & Dataframes

In [9]:
# pd.Series()--create 1D labeled array
s=pd.Series([10,20,30],index=['a','b','c'],name='values')
s

a    10
b    20
c    30
Name: values, dtype: int64

In [2]:
#pd.DataFrame() from a dict of lists-create a labeled 2D table
df=pd.DataFrame({
    'name':['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['NY','LA','SF','NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [12]:
#pd.DataFrame()--From a list of dicts
pd.DataFrame([{'a':1,'b':2},{'a':3,'b':4}])

   a  b
0  1  2
1  3  4

In [13]:
#pd.DataFrame() from a Numpy array
pd.DataFrame(np.arange(6).reshape(2,3),columns=['x','y','z'])

   x  y  z
0  0  1  2
1  3  4  5

### 3.Attributes & Inspection

In [17]:
# returns the how many rows and columns in table
df.shape

(4, 3)

In [16]:
#column labels
df.columns

Index(['name', 'age', 'city'], dtype='str')

In [20]:
# rows labels
df.index

RangeIndex(start=0, stop=4, step=1)

In [21]:
#data type of each column
df.dtypes

name      str
age     int64
city      str
dtype: object

In [24]:
#underlying Numpy array all values present in table
df.values

array([['Alice', 25, 'NY'],
       ['Bob', 30, 'LA'],
       ['Charlie', 35, 'SF'],
       ['David', 40, 'NY']], dtype=object)

In [25]:
#total number of elements
df.size

12

In [29]:
# frist n rows default is first 5 rows
df.head(2)

    name  age city
0  Alice   25   NY
1    Bob   30   LA

In [30]:
# tail n rows default is first 5 rows
df.tail(2)

      name  age city
2  Charlie   35   SF
3    David   40   NY

In [32]:
# summary of the dataframe(dtype,non null counts)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   city    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [34]:
# statistical summary of numerical columns
df.describe()

             age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

In [36]:
# memory used by each coumn
df.memory_usage()

Index    132
name      32
age       32
city      32
dtype: int64

### 4. Selection & Indexing(loc,iloc,at,iat)

In [50]:
#set a column as the row index
df.set_index('name',inplace=False)

         age city
name
Alice     25   NY
Bob       30   LA
Charlie   35   SF
David     40   NY

In [49]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [4]:
# column selection- single column returns a series
df['age']

0    25
1    30
2    35
3    40
Name: age, dtype: int64

In [6]:
# column selection- a list of columns returns a DataFrame
df[['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [8]:
#select a row by label
df.loc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [10]:
# select a scalar value by label
df.loc[0,'age']

np.int64(25)

In [11]:
df.loc[3,'age']

np.int64(40)

In [12]:
# select rows and columns by label
df.loc[0:2,['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [13]:
# select a row by integer position
df.iloc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [15]:
# select a scalar value by integer position
df.iloc[0,1]

np.int64(25)

In [16]:
# select rows & columns by integer position
df.iloc[0:2,0:2]

    name  age
0  Alice   25
1    Bob   30

In [20]:
# fast scalar access by label
df.at[0,'age']

np.int64(25)

In [21]:
# fast scalar access by integer position
df.iat[0,1]

np.int64(25)

### 5.Filtering & Boolean Indexing

In [22]:

df[df['age']>28]

      name  age city
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [23]:
# multiple conditions-combine with & (and)/|(or)
df[(df['age']>25)&(df['city']=='NY')]

    name  age city
3  David   40   NY

In [26]:
df[(df['age']>25)|(df['city']=='NY')]

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [31]:
# filter rows where a column matches a set of values
df[df['city'].isin(['NY','LA'])]

    name  age city
0  Alice   25   NY
1    Bob   30   LA
3  David   40   NY

In [35]:
# filter using a readable string expression
df.query('age>28 and city == "NY"')

    name  age city
3  David   40   NY

In [37]:
# keep matching values,replace others with NaN
df.where(df['age']>28)

      name   age city
0      NaN   NaN  NaN
1      Bob  30.0   LA
2  Charlie  35.0   SF
3    David  40.0   NY

In [39]:
# where not
df.mask(df['age']>28)

    name   age city
0  Alice  25.0   NY
1    NaN   NaN  NaN
2    NaN   NaN  NaN
3    NaN   NaN  NaN

### 6. Adding, Modifying & Dropping Columns/Rows

In [54]:
df2=df.copy()
df2

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [55]:
# Adding a new column from a existing one
df2['senior']=df2['age']+2
df2

      name  age city  senior
0    Alice   25   NY      27
1      Bob   30   LA      32
2  Charlie   35   SF      37
3    David   40   NY      42

In [56]:
df2['senior']=df2['age']>30
df2

      name  age city  senior
0    Alice   25   NY   False
1      Bob   30   LA   False
2  Charlie   35   SF    True
3    David   40   NY    True

In [57]:
# Adding a computed column
df2['age_plus_5']=df2['age']+5
df2

      name  age city  senior  age_plus_5
0    Alice   25   NY   False          30
1      Bob   30   LA   False          35
2  Charlie   35   SF    True          40
3    David   40   NY    True          45

In [58]:
#rename columns
df2.rename(columns={'city':'location'},inplace=True)
df2

      name  age location  senior  age_plus_5
0    Alice   25       NY   False          30
1      Bob   30       LA   False          35
2  Charlie   35       SF    True          40
3    David   40       NY    True          45

In [59]:
#drop column
df2.drop(columns=['age_plus_5'],inplace=True)
df2

      name  age location  senior
0    Alice   25       NY   False
1      Bob   30       LA   False
2  Charlie   35       SF    True
3    David   40       NY    True

In [60]:
#drop row
df2.drop(index=0,inplace=False)

      name  age location  senior
1      Bob   30       LA   False
2  Charlie   35       SF    True
3    David   40       NY    True

In [63]:
# insert a column at a specific position
df2.insert(1,'id',range(len(df2)))
df2

ValueError: cannot insert id, already exists

In [64]:
df2

      name  id  age location  senior
0    Alice   0   25       NY   False
1      Bob   1   30       LA   False
2  Charlie   2   35       SF    True
3    David   3   40       NY    True

In [65]:
df2.assign(double_age=df2['age']*2)

      name  id  age location  senior  double_age
0    Alice   0   25       NY   False          50
1      Bob   1   30       LA   False          60
2  Charlie   2   35       SF    True          70
3    David   3   40       NY    True          80

### 7.Handling Missing Data

In [3]:
df_na=pd.DataFrame({'a':[1,np.nan,3],'b':[np.nan,2,3]})
df_na

     a    b
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0

In [5]:
# is.na()--boolean mask of misssing values
df_na.isna()

       a      b
0  False   True
1   True  False
2  False  False

In [6]:
#.notna()--opposite of .isna()
df_na.notna()

       a      b
0   True  False
1  False   True
2   True   True

In [7]:
#count missing values per column
df_na.isnull().sum()

a    1
b    1
dtype: int64

In [8]:
#drop rows containing any NaN
df_na.dropna()

     a    b
2  3.0  3.0

In [9]:
# drop column containing any NaN
df_na.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [11]:
# fill missing  values with a constant
df_na.fillna(0)

     a    b
0  1.0  0.0
1  0.0  2.0
2  3.0  3.0

In [15]:
# forward  fill missing values with 1 not in 1 row
df_na.ffill()

     a    b
0  1.0  NaN
1  1.0  2.0
2  3.0  3.0

In [14]:
#backward fill missing values
df_na.bfill()

     a    b
0  1.0  2.0
1  3.0  2.0
2  3.0  3.0

### 8.Sorting & Ranking

In [2]:
df=pd.DataFrame({
    'name':['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['NY','LA','SF','NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [18]:
df.sort_values('age')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [21]:
# sort by multiple columns
df.sort_values(['city','age'],ascending=[True,False])

      name  age city
1      Bob   30   LA
3    David   40   NY
0    Alice   25   NY
2  Charlie   35   SF

In [24]:
# .sort_index() sort rows by the index
df.sort_index()

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [26]:
# rank values within a column
df['age'].rank()

0    1.0
1    2.0
2    3.0
3    4.0
Name: age, dtype: float64

In [27]:
# top n rows by a column
df.nlargest(2,'age')

      name  age city
3    David   40   NY
2  Charlie   35   SF

In [28]:
# bottom n rows by a column
df.nsmallest(2,'age')

    name  age city
0  Alice   25   NY
1    Bob   30   LA

### 9. Aggregation & Statistics

In [29]:
df['age'].sum(),df['age'].mean(),df['age'].median()

(np.int64(130), np.float64(32.5), np.float64(32.5))

In [30]:
df['age'].std(),df['age'].var()

(np.float64(6.454972243679028), np.float64(41.666666666666664))

In [31]:
df['age'].min(),df['age'].max()

(np.int64(25), np.int64(40))

In [32]:
df['age'].count()

np.int64(4)

In [35]:
# apply multiple aggregation functions at once
df.agg({'age':['mean','max','min']})

       age
mean  32.5
max   40.0
min   25.0

In [37]:
# correalation matrix of numeric columns
df.corr(numeric_only=True)

     age
age  1.0

In [39]:
# most  frequently occuring value
df['city'].mode()

0    NY
Name: city, dtype: str

### 10. GroupBy Operations

In [3]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [4]:
g=df.groupby('city')

In [5]:
g

In [6]:
# number of rows in each group
g.size()

city
LA    1
NY    2
SF    1
dtype: int64

In [7]:
#group then aggregates a single column
g['age'].mean()

city
LA    30.0
NY    32.5
SF    35.0
Name: age, dtype: float64

In [8]:
# agg() on a groupby multiply aggregations per group
g.agg({'age':['mean','sum']})

       age
      mean sum
city
LA    30.0  30
NY    32.5  65
SF    35.0  35

In [9]:
# on a groupby-custom function per group
g.apply(lambda x:x['age'].max()-x['age'].min())

city
LA     0
NY    15
SF     0
dtype: int64

In [10]:
add=lambda a,b:a+b

In [11]:
add(4,5)

9

In [12]:
# iterating over groupd with a for loop
for name,group in g:
    print(name)
    print(group)

LA
  name  age city
1  Bob   30   LA
NY
    name  age city
0  Alice   25   NY
3  David   40   NY
SF
      name  age city
2  Charlie   35   SF

In [14]:
#get_group() retrive a specific group
g.get_group('NY')

    name  age city
0  Alice   25   NY
3  David   40   NY

In [16]:
#converting a data to csv
df.to_csv('data.csv',index=False)
pd.read_csv('data.csv')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [18]:
#.to_json()/pd.read_json()-write and read json files
df.to_json('data.json',orient='records')
pd.read_json('data.json')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [19]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 26.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
#.to_excel()/pd.read_excel()-write and read json files(needs openpyxl)
df.to_excel('data.xlsx',index=False)
pd.read_excel('data.xlsx')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [21]:
# to_dict() - converts a dataframe to a list of dicts
df.to_dict(orient='records')

[{'name': 'Alice', 'age': 25, 'city': 'NY'},
 {'name': 'Bob', 'age': 30, 'city': 'LA'},
 {'name': 'Charlie', 'age': 35, 'city': 'SF'},
 {'name': 'David', 'age': 40, 'city': 'NY'}]

In [23]:
#pd.DataFrame.from_dict()--build a dataframe from a dict
pd.DataFrame.from_dict({'a':[1,2]})

   a
0  1
1  2